menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/syxc
    GitHub: https://github.com/syxc
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: syxc
duoshuo:

# Analytics
# google-analytics:
ga: UA-74437073-1

# Copyright Infomation
startyear: 2015
